data<-read.csv("Montserrat Species Length Composition Data_July2.csv")
names(data)
days<-length(unique(data$Date))
boats<-length(unique(data$Vessel.ID..Length))
area<-length(unique(data$Area.fished))
unique(df[c("data$Date","data$Vessel.ID..Length")])
trips<-data.frame(data$Date,data$Vessel.ID..Length)
unique_trips<-unique(trips)
nrow(unique_trips)
nrow(trips)
gears<-unique(data$Gear.Type)
